name: 自动同步上游 MoonTVPlus
on:
  workflow_dispatch:  # 允许手动点一下运行
  schedule:
    - cron: "0,10,20,30,40,50 * * * *"  # 每 10 分钟检查一次更新

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 同步上游最新代码
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: mtvpls/MoonTVPlus
          upstream_sync_branch: main
          target_sync_branch: main
          test_mode: false
